### PR TITLE
Pathways Network Graph improvements

### PR DESCRIPTION
**Pull request by jtlong3rd**
This PR addresses some outstanding redmines re: our Pathways Network Graphs:

* https://redmine.apidb.org/issues/41627
* https://redmine.apidb.org/issues/41630
* https://redmine.apidb.org/issues/20017

**More specifically:**
* In the graph itself, HTML is stripped from the node label (HTML is *not* stripped from the node details)
* The Layouts menu has been removed, and the associated code cleaned up
* There is now a "reset" button which will clear all node painting and reset the node positions + zoom level
* There is now a checkbox which, when checked, disables the mouse zoom gesture (i.e., "enable[s] scrolling").
* There is now a searchbar for query node names/IDs
* One can search names and IDs for a specific free-text phrase; autocomplete for names/IDs is also offered

**Lingering issues:**
* The Cytoscape version has been fixed at 3.2.9. (I encountered an issue with how certain nodes were rendering when I attempted a ^3.2.9, and even ~3.2.9, upgrade.)
* We can likely remove the `cytoscape-dagre` dependency

### CODE REVIEW

**Comment by kathryncrouch** [comment]
I have reviewed these changes on the front-end and functionality looks good, there one lingering UI issue with a clash between the search box and the reset that Jamie knows about.  I have not reviewed the code.

**Comment by dmfalke** [comment]
I reviewed the code, and it looks great. I don't see any issues there.

There are a couple of issues I'd like to raise with the UI

1. I think the logic for the "Enable Scrolling" button is revered.
2. It isn't clear at first what the reset button does. Can that be changed to "Reset layout"?
3. If the search matches multiple nodes (e.g., free text), should the node details dialog close?

Other than that, I think this looks great!

**Comment by kathryncrouch** [comment]
1. Do you mean reversed?  This made sense to me with my mouse wheel behaviour.  If the button is not checked, then using the mouse wheel zooms the pathway map in and out.  When "Enable scrolling" is checked, it scrolls up and down the page instead. UI may be different with different mouse/trackpad devices though and I can see that it might be confusing. Maybe "Disable Mouse Zoom" or something would be clearer? Need to be a bit careful because you can still zoom using the controls in the left corner and you don't want to imply that this is no longer possible.
2.  I found this clear - but then again I asked for the functionality so I knew what to expect.  Can't see any harm in making this more explicit.
3.  Yes, good point.  If a node popup is open, either as a result of running a prior search or opening it manually, it is confusing to leave it open if the search returns multiple nodes.

**Comment by dmfalke** [comment]
I did mean "reversed" :). I assumed the checkbox meant "enable scroll gestures". Maybe we can change the text and reverse the logic? Or maybe I'm an outlier?

**Comment by kathryncrouch** [comment]
Good, I did spend a couple of minutes wondering if "revered" logic was some technical term I was unaware of :)

We will run these changes through UX as well, the verbiage is perhaps something for debate there. The actual behaviour is nice either way!

**Comment by jtlong3rd** [comment]
Thanks for reviewing @dmfalke! Here's what I propose: 

1. I like @kathryncrouch  suggestion having the toggle text refer to "Mouse Zooming" instead of scrolling.
2. I'm fine with changing the "Reset" button verbiage to "Reset layout." I'm sure UX will want to weigh in on the verbiage as well.
3. I think closing the node details when multiple nodes are matched is a good idea. Indeed, it could be confusing to have the node details remain open, especially when the open details are for a node that wasn't matched.

**Comment by jtlong3rd** [comment]
PR updated!

**Comment by kathryncrouch** [comment]
I'm getting a "We're sorry, something went wrong" error when I load or refresh pathway record pages on your dev site now @jtlong3rd . If I dismiss the error, everything behaves as expected and looks good.

**Comment by dmfalke** [comment]
> 3. I think closing the node details when multiple nodes are matched is a good idea. Indeed, it could be confusing to have the node details remain open, especially when the open details are for a node that wasn't matched.

It occurs to me that users can open the dialog by clicking on a node. This is making me think that we should never automatically open the dialog. There are three reasons:

1. It detracts from the green border highlighting.
2. For multiple matches, where the dialog isn't opened, it might appear that no nodes matched.
3. The user might have opened details for a different node and not want it to be closed or replaced with a different node.

Also, I think it might help to have some text indicating that matching nodes are highlighted with a green border.

**Comment by jtlong3rd** [comment]
@kathryncrouch It's unrelated! Thanks for checking.

**Comment by jtlong3rd** [comment]
@dmfalke I think 3 is an especially good point as to why automatically opening/closing node details could be an issue.

If I got rid of the automatic opening/closing of node details, the behavior would become "highlight the matched nodes and center on them." That feel "good enough" to me.

**Comment by kathryncrouch** [comment]
Agreed, @dmfalke's points are good, removing this behaviour makes sense.

**Comment by jtlong3rd** [comment]
The "automatic opening/closing of node details" behavior has been removed.

**Comment by jtlong3rd** [comment]
Note to our future selves: a followup PR will be opened to address lingering feedback from this PR and any feedback that arises in UX tomorrow.

**Pull request merged**
